<?php

namespace AppBundle\Repository;


use AppBundle\Entity\Banishment;
use AppBundle\Entity\Course;
use Doctrine\ORM\EntityRepository;

/**
 * RideRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class BanishmentRepository extends EntityRepository
{
    /**
     * @return array
     * @throws \Exception
     */
    public function findActiveExpired()
    {
        return $this->createQueryBuilder("a")
            ->where("a.finishTime < :now")
            ->setParameter("now", new \DateTime)
            ->getQuery()
            ->getResult();
    }
}
